// src/components/sections/project.tsx
import React from "react";
import { InfoSection } from "../InfoSection";
import { ProjectCard } from "../ProjectCard";
import { projects } from "../../configs/data";

export const ProjectSection = () => {
  return (
    <InfoSection id="projects">
      <div className="flex h-full flex-row mt-4">
        <div className="flex flex-wrap justify-center">
          {projects.map((project, index) => (
            <ProjectCard
              key={index}
              description={project.description}
              title={project.title}
              techStack={project.techStack}
              url={project.url}
              repoLink={project.repoLink}
            />
          ))}
        </div>
      </div>
    </InfoSection>
  );
};

// src/lib/components/sections/project.svelte
<script lang="ts">
	import { projects } from '../../../configs/data';
	import InfoSection from '../InfoSection.svelte';
	import ProjectCard from '../ProjectCard.svelte';
</script>

<InfoSection id="projects">
	<div class="flex h-full flex-row mt-4">
		<div class="flex flex-wrap justify-center">
			{#each projects as project, index}
				<ProjectCard
					description={project.description}
					title={project.title}
					techStack={project.techStack}
					url={project.url}
					repoLink={project.repoLink}
				/>
			{/each}
		</div>
	</div>
</InfoSection>
