// src/components/sections/skills.tsx
import React from "react";
import { skills } from "../../configs/data";
import { InfoSection } from "../InfoSection";
import { SkillItem } from "../SkillItem";

export const SkillsSection = () => {
  return (
    <InfoSection id="skills">
      <div className="flex h-full flex-col space-y-8 pt-4">
        {skills.map((skill, index) => (
          <SkillItem key={index} title={skill.title} items={skill.items} />
        ))}
      </div>
    </InfoSection>
  );
};

// src/lib/components/sections/skills.svelte
<script lang="ts">
	import { skills } from '../../../configs/data';
	import InfoSection from '../InfoSection.svelte';
	import SkillItem from '../SkillItem.svelte';
</script>

<InfoSection id="skills">
	<div class="flex h-full flex-col space-y-8 pt-4">
		{#each skills as skill}
			<SkillItem title={skill.title} items={skill.items} />
		{/each}
	</div>
</InfoSection>
