// src/lib/components/sections/contact.svelte
<script lang="ts">
	import { socials } from '../../../configs/data';
	import InfoSection from '../InfoSection.svelte';
	import SocialMediaCard from '../SocialMediaCard.svelte';
</script>

<InfoSection id="contact">
	<div class="flex h-full flex-row flex-wrap md:flex-nowrap space-y-4 md:space-y-0 mt-8">
		{#each socials as social}
			<SocialMediaCard
				description={social.description}
				url={social.url}
				iconClass={social.iconClass}
				linkText={social.linkText}
			/>
		{/each}
	</div>
</InfoSection>

// src/components/sections/contact.tsx
import React from "react";
import { InfoSection } from "../InfoSection";
import { SocialMediaCard } from "../SocialMediaCard";
import { socials } from "../../configs/data";
export const ContactSection = () => {
  return (
    <InfoSection id="contact">
      <div className="flex h-full flex-row flex-wrap md:flex-nowrap space-y-4 md:space-y-0 mt-8">
        {socials.map((social, index) => (
          <SocialMediaCard
            key={index}
            description={social.description}
            url={social.url}
            iconClass={social.iconClass}
            linkText={social.linkText}
          />
        ))}
      </div>
    </InfoSection>
  );
};
