// src/components/SocialMediaCard.tsx
import { FC } from "react";
import Link from "next/link";
import { classes } from "../configs/classnames";

interface SocialMediaCardProps {
  url: string;
  iconClass: string;
  description: string;
  linkText: string;
}

export const SocialMediaCard: FC<SocialMediaCardProps> = ({
  description,
  iconClass,
  url,
  linkText,
}) => {
  return (
    <a
      target="_blank"
      href={url}
      rel="noreferrer"
      className={`p-4 mx-8 md:mx-3 w-full md:w-1/4 flex flex-col justify-between  text-center rounded shadow-2xl ${classes.background.dark} hover:transform duration-200`}
      role="button"
    >
      <h4 className={`text-xl ${classes.textWhite}`}>
        <i className={`${iconClass} fa-2x`}></i>
      </h4>
      <p>{description}</p>
      <p className={classes.textAccent}>{linkText}</p>
    </a>
  );
};

// src/lib/components/SocialMediaCard.svelte
<script lang="ts">
	import { classes } from '../../configs/classnames';
	export let url: string;
	export let iconClass: string;
	export let description: string;
	export let linkText: string;
</script>

<div
	class={`p-4 mx-8 md:mx-3 w-full md:w-1/4 flex space-y-4 flex-col justify-between text-center rounded shadow-2xl ${classes.background.dark} duration-200 ${classes.hoverShadowAccent}`}
>
	<h4 class={`text-xl ${classes.textWhite}`}>
		<i class={`${iconClass} fa-2x`} />
	</h4>
	<p>{description}</p>
	<div class="flex items-center justify-center">
		<a
			target="_blank"
			href={url}
			rel="noreferrer"
			class={`${classes.textAccent} ${classes.underline}`}
		>
			{linkText}
		</a>
	</div>
</div>
